### ISSUE TITLE
Reducing Codes

### ISSUE THREAD

**Issue by Brsrld** [paloamit/SwiftUI-Animations#1]
Hi great job.Thanks for all animations. I want to mention something. Using @viewbuilder function you can reduce your repeading codes.

**Comment by paloamit** [comment]
Hi @Brsrld thanks a lot for highlighting it. Even I am also new to SwiftUI and I am also learning lot's of new things related to swiftUI. While, doing those animations I didn't knew about **custom ViewBuilders** but now as i am aware of this custom **ViewBuilders**, I will try to optimise the same in my future animations. Thank You.

**Comment by Brsrld** [comment]
You are welcome. Good luck...
